### ISSUE TITLE
Error while add any platform.

### ISSUE THREAD

**Issue by KingAndroid** [terikon/cordova-plugin-photo-library#107]
```
Failed to install 'cordova-plugin-photo-library': CordovaError: Version of installed plugin: "cordova-plugin-file@5.0.0" does not satisfy dependency plugin requirement "cordova-plugin-file@^4.3.2". Try --force to use installed plugin as dependency.
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:557:37
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Failed to restore plugin "cordova-plugin-photo-library" from config.xml. You might need to try adding it again. Error: Version of installed plugin: "cordova-plugin-file@5.0.0" does not satisfy dependency plugin requirement "cordova-plugin-file@^4.3.2". Try --force to use installed plugin as dependency.
```

**Comment by lentyaishe** [comment]
Happens to me too. There are other cordova plugins that require `cordova-plugin-file` of version `5.0.0`. Can you update your `plugin.xml` with `<dependency id="cordova-plugin-file" version="^5.0.0"/>` to fix this issue?

**Comment by RHinderiks** [comment]
Any info on when cordova-plugin-file@5.0.0 will be supported ?

**Comment by davidgv88** [comment]
some info?

**Comment by NareshKukreti12** [comment]
Have you found solution. I am having same issue
**Failed to install "cordova-plugin-photo-library":"CordovaError: Version of installed plugin:"cordova-plugin-file@6.0.1" does not satisfy dependency plugin requirement "cordova-plugin-file@^4.3.2'. Try --force to use installed plugin as dependency .**

**Cli packages**
   ionic/cli-utils:1.19.1
   ionic (ionic CLI): 3.19.1

**Global Packages:**
cordova (Cordova CLI) : 8.0.0

Local Packages:
 
ionic/app-scripts: 3.1.6
Cordova Platforms : ios 4.5.4


**DEPENDECIES**
cordova-plugin-add-swift-support: 1.7.1
cordova-plugin-camera: 3.0.0
cordova-plugin-file: 6.0.1


Tried forcing ( cordova-plugin-file@4.3.2),  got next error  
Cannot find module'../cordova/platform_metadata'

**Comment by lentyaishe** [comment]
@NareshKukreti12 Look at my pull request that is still open from Dec 11 on how to fix it. You may clone this repo locally and then fix it locally and use your local version of the plugin until it will be officially fixed if ever..

**Comment by NareshKukreti12** [comment]
@lentyaishe issue fixed, but now got next error.
You can see list of errors
1- PhotoLibraryProtocol.swift:133:5: error: expected declaration
    fileprivate func sendErrorResponse(_ statusCode: Int, error: String) {
2- PhotoLibraryProtocol.swift:133:16: error: consecutive declarations on a line must be separated by ';'
    fileprivate func sendErrorResponse(_ statusCode: Int, error: String) {
3- PhotoLibraryProtocol.swift:138:5: error: expected declaration
    fileprivate func sendResponseWithResponseCode(_ statusCode: Int, data: Data?, mimeType: String?) {
4- PhotoLibraryProtocol.swift:138:16: error: consecutive declarations on a line must be separated by ';'
    fileprivate func sendResponseWithResponseCode(_ statusCode: Int, data: Data?, mimeType: String?) {



** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/pRMInfotech/Documents/HANUMENDRA/TECHNOLOGY/IONIC/Projects/Piciris-14-Feb/platforms/ios/Piciris/Plugins/cordova-plugin-photo-library/PhotoLibrary.swift
	CompileSwift normal x86_64 /Users/pRMInfotech/Documents/HANUMENDRA/TECHNOLOGY/IONIC/Projects/Piciris-14-Feb/platforms/ios/Piciris/Plugins/cordova-plugin-photo-library/PhotoLibraryProtocol.swift
	CompileSwift normal x86_64 /Users/pRMInfotech/Documents/HANUMENDRA/TECHNOLOGY/IONIC/Projects/Piciris-14-Feb/platforms/ios/Piciris/Plugins/cordova-plugin-photo-library/PhotoLibraryService.swift
	CompileSwift normal x86_64 /Users/pRMInfotech/Documents/HANUMENDRA/TECHNOLOGY/IONIC/Projects/Piciris-14-Feb/platforms/ios/Piciris/Plugins/cordova-plugin-photo-library/PhotoLibraryGetLibraryOptions.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(5 failures)

**Comment by lentyaishe** [comment]
@NareshKukreti12 Sorry, can't help you further. I'm not the plugin creator and I don't know SWIFT unfortunately. Try to Google it or open the non-compiling files in any code editor and try to figure out what could be the reason for the build error. From the log you provided it doesn't seem to be too complicated.

**Comment by jeffcordova** [comment]
hi @lentyaishe, im also getting stuck here when i reformatted my laptop. Where do I see that plugin.xml file?

**Comment by lentyaishe** [comment]
@jeffcordova `plugin.xml` fiel is always in the root folder of the plugin.

**Comment by akhachaturyan** [comment]
I don't know if anyone might concern but I had a similar issue with `cordova-plugin-photokandy-video-thumbnail` library, which was requiring only <5 version of `cordova-file plugin`. As a result, I spent several hours trying to change versions of both to match, even did force install of the photo library, but... It turned out that there were devices(LG V30) which was crashing(bed effect of force install).
What can I suggest? 
I did change the library(to `cordova-plugin-video-thumbnail`) and that was the solution.
